CREATE DATABASE [fractuz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fractuz', FILENAME = N'/var/opt/mssql/data/fractuz.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fractuz_log', FILENAME = N'/var/opt/mssql/data/fractuz_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [fractuz] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [fractuz] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [fractuz] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [fractuz] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [fractuz] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [fractuz] SET ARITHABORT OFF 
GO
ALTER DATABASE [fractuz] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [fractuz] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [fractuz] SET AUTO_CREATE_STATISTICS OFF
GO
ALTER DATABASE [fractuz] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [fractuz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [fractuz] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [fractuz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [fractuz] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [fractuz] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [fractuz] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [fractuz] SET  DISABLE_BROKER 
GO
ALTER DATABASE [fractuz] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [fractuz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [fractuz] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [fractuz] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [fractuz] SET  READ_WRITE 
GO
ALTER DATABASE [fractuz] SET RECOVERY FULL 
GO
ALTER DATABASE [fractuz] SET  MULTI_USER 
GO
ALTER DATABASE [fractuz] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [fractuz] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [fractuz] SET DELAYED_DURABILITY = DISABLED 
GO
USE [fractuz]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [fractuz] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
